[tool.poetry]
name = "gato"
version = "0.1.0"
description = "A remarkably fast asynchronous web framework for Python."
authors = ["Elliott Maguire <me@elliott-m.com>"]
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.7"
cython = "^0.29.12"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "=19.3b0"
flake8 = "^3.7"

[tool.black]
line-length = 79
include = '\.pyx?$'

[tool.flake8]
ignore = 'E203, E266, E501, W503, F403, F401'
max-line-length = 79
max-complexity = 18
select = 'B,C,E,F,W,T4,B9'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
